### PR TITLE
Address issue #116

### PR DESCRIPTION
**Pull request by Reshad-Rahman**
Also change yang semver in the YANG modules to 05

### CODE REVIEW

**Comment by Reshad-Rahman** [comment]
@xorrkaz , I believe you are uploading this document when things reopen on Monday. So, assuming changes here are good, please do so after this is merged.

**Review by xorrkaz — APPROVED** [review]
Looks good to me.  Yes, I can merge and upload -05.  Looks like you already bumped the draft revision.

**Comment by Reshad-Rahman** [comment]
> Oops. Didn't realize you were opening another issue & PR for this until I already fixed it in my PR.

Jason, I am fixing this in module-versioning, your PR was only for semver right?

**Comment by jsterne** [comment]
> > Oops. Didn't realize you were opening another issue & PR for this until I already fixed it in my PR.
> 
> Jason, I am fixing this in module-versioning, your PR was only for semver right?

I only fixed Semver (didn't realize you were talking about module versioning as well)

**Pull request merged**
